### ISSUE TITLE
[DLB]2018-01-20  질문사항

### ISSUE THREAD

**Issue by projokim** [YBIGTA/DLB#1]
DLB/Neural Networks and Deep Learning/1. Welcom to the Deep Learning.md

**Comment by statkim7578** [comment]
![11](https://user-images.githubusercontent.com/34841210/35153202-65b3bf5a-fd1d-11e7-9ef8-278c20a05fc7.PNG)

'실제 설계에서 Neural Network 의 중간 레이어는 의미를 가지지 않는다' 라는 말은 왜 그런것인가요?
